# src/Musee/BilletterieBundle/Resources/config/routing.yml
musee_billetterie_home:
    path:    /Accueil
    defaults:    { _controller: MuseeBilletterieBundle:Formulaire:index }
panier:
    path:    /panier/{id}
    defaults:    { _controller: MuseeBilletterieBundle:Formulaire:paiement }
    requirements:
        id: \d+  
visiteurs_form:
    path:    /visiteurs/{id}/{commande_id}
    defaults:    { _controller: MuseeBilletterieBundle:Formulaire:addVisiteurs }
    requirements:
        id: .+
musee_email:
    path:    /Email/{id}
    defaults:    { _controller: MuseeBilletterieBundle:Formulaire:email }
    requirements:
        id: .+