# src/Musee/BilletterieBundle/Resources/config/services.yml


services:

    musee_billetterie.prix:

        class: Musee\BilletterieBundle\Services\Prix
        
    musee_billetterie.stripe:

        class: Musee\BilletterieBundle\Services\Stripe