# src/Musee/BilletterieBundle/Resources/config/services.yml


services:

    musee_billetterie.prix:

        class: Musee\BilletterieBundle\Services\Prix
        
    musee_billetterie.stripe:

        class: Musee\BilletterieBundle\Services\Stripe
        
    musee_billetterie.validator.dateReservation:                              # Le nom du service

        class: Musee\BilletterieBundle\Services\Validator\DateReservationValidator     # La classe du service, ici notre validateur déjà créé

        arguments: ["@request_stack", "@doctrine.orm.entity_manager"] # Les données qu'on injecte au service : la requête et l'EntityManager

        tags:

            - { name: validator.constraint_validator, alias: musee_billetterie_dateReservation }  # C'est avec l'alias qu'on retrouvera le service