musee_billetterie:
    resource: "@MuseeBilletterieBundle/Resources/config/routing.yml"
    prefix:   /

oc_plateform:
    resource: "@OCPlateformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
